# Channel Onboarding — set up a new messaging channel with staged approval gates.
# Staged recipe: human-in-loop at each stage for verification.
# Usage: recipes execute letsgo:recipes/channel-onboard.yaml context='{"channel_type":"telegram","channel_name":"my-bot"}'

name: channel-onboard
description: Set up a new messaging channel with authentication, pairing, and verification
version: 2.0.0
author: letsgo
tags:
  - channels
  - onboarding
  - setup
  - messaging

context:
  channel_type: ""
  channel_name: ""

stages:
  - name: configure
    steps:
      - id: validate-channel-type
        agent: self
        prompt: |
          Validate the channel configuration request.

          Channel type: {{channel_type}}
          Channel name: {{channel_name}}

          Supported channels and their requirements:

          **Built-in channels (no extra install):**

          **webhook**:
          - Endpoint URL
          - Shared secret for HMAC verification
          - Optional: custom headers, retry policy

          **whatsapp**:
          - No API credentials needed (QR code auth)
          - Optional: session_dir, files_dir paths
          - Requires: Node.js installed on system

          **Optional built-in (require pip install letsgo-gateway[name]):**

          **telegram**:
          - Bot token (from @BotFather)
          - Optional: webhook URL, allowed user IDs
          - Install: pip install letsgo-gateway[telegram]

          **discord**:
          - Bot token (from Discord Developer Portal)
          - Guild ID (server to connect to)
          - Optional: channel ID, role permissions
          - Install: pip install letsgo-gateway[discord]

          **slack**:
          - Bot token (xoxb-...)
          - Signing secret
          - Optional: App-Level Token for Socket Mode (xapp-...)
          - Install: pip install letsgo-gateway[slack]

          **Plugin channels (separate packages):**

          **signal**:
          - Phone number registered with Signal
          - Requires: signal-cli installed on system
          - Install: pip install letsgo-channel-signal

          **matrix**:
          - Homeserver URL (e.g., https://matrix.org)
          - User ID (e.g., @letsgo:matrix.org)
          - Access token
          - Install: pip install letsgo-channel-matrix[nio]

          **teams**:
          - Microsoft App ID (from Azure Bot registration)
          - Microsoft App Password
          - Install: pip install letsgo-channel-teams[botbuilder]

          **line**:
          - Channel access token (from LINE Developers Console)
          - Channel secret
          - Install: pip install letsgo-channel-line[sdk]

          **googlechat**:
          - Service account JSON key file path
          - Space name (e.g., spaces/AAAA...)
          - Install: pip install letsgo-channel-googlechat[sdk]

          **imessage**:
          - Apple ID (macOS only)
          - Requires: macOS with Messages.app configured
          - Install: pip install letsgo-channel-imessage

          **nostr**:
          - Private key (hex or nsec format)
          - Relay URLs (list of WebSocket URLs)
          - Install: pip install letsgo-channel-nostr[sdk]

          **irc**:
          - Server hostname (e.g., irc.libera.chat)
          - Port (default: 6697), Nick, Channel (e.g., #letsgo)
          - Install: pip install letsgo-channel-irc[sdk]

          **mattermost**:
          - Server URL (e.g., https://mattermost.example.com)
          - Personal access token or bot token
          - Team ID
          - Install: pip install letsgo-channel-mattermost[sdk]

          **twitch**:
          - OAuth token (oauth:...)
          - Channel name to join
          - Install: pip install letsgo-channel-twitch[sdk]

          **feishu**:
          - App ID (from Feishu Open Platform)
          - App secret
          - Install: pip install letsgo-channel-feishu[sdk]

          If channel_type is empty or unsupported, list all supported types and ask the user to choose.
          If the channel is a plugin channel, check if the package is installed. If not, install it.
          If channel_type is valid, list the required credentials for this channel type.
          Validate the format of any provided values (don't test connectivity yet).

          Report: channel type confirmed, credentials needed, any values already provided.
        output: channel_config
        timeout: 300

    approval:
      required: true
      prompt: |
        Channel type: {{channel_type}} ({{channel_name}})

        {{channel_config}}

        Proceed to test authentication with these settings?

  - name: authenticate
    steps:
      - id: store-credentials
        agent: self
        prompt: |
          Store the channel credentials securely.

          Channel: {{channel_type}} ({{channel_name}})
          Configuration: {{channel_config}}

          Use tool-secrets to store each credential:
          - Name format: channel/{{channel_type}}/{{channel_name}}/<credential-name>
          - Category: api_key

          Report which credentials were stored (names only, never values).
        output: credential_storage
        timeout: 120

      - id: test-auth
        agent: self
        prompt: |
          Test authentication for the configured channel.

          Channel: {{channel_type}} ({{channel_name}})
          Stored credentials: {{credential_storage}}

          Steps:
          1. Retrieve credentials from tool-secrets
          2. Attempt to authenticate with the channel's API
          3. Verify the bot/webhook identity and permissions
          4. Report: connection status, bot identity, available permissions

          If authentication fails, report the error clearly with troubleshooting steps.
        output: auth_result
        timeout: 120

      - id: pair-device
        agent: self
        prompt: |
          Perform device pairing for the {{channel_type}} channel "{{channel_name}}".

          Authentication result: {{auth_result}}

          Pairing steps by channel type:
          - **Telegram**: Send a test message to the bot, verify receipt
          - **Discord**: Send a message in the configured guild, verify receipt
          - **Slack**: Post a test message to a channel, verify receipt
          - **Webhook**: Send a test payload to the endpoint, verify response
          - **WhatsApp**: Generate QR code, wait for scan, verify connection
          - **Signal**: Send a test message to the registered number, verify receipt
          - **Matrix**: Join a test room, send a message, verify receipt
          - **Teams**: Send a test message via Bot Framework, verify receipt
          - **LINE**: Send a test message via Messaging API, verify receipt
          - **Google Chat**: Post a test message to the configured space, verify receipt
          - **iMessage**: Send a test iMessage via Messages.app, verify receipt (macOS only)
          - **Nostr**: Publish a test note to configured relays, verify receipt
          - **IRC**: Join configured channel, send a test message, verify receipt
          - **Mattermost**: Post a test message to configured team channel, verify receipt
          - **Twitch**: Send a test chat message to configured channel, verify receipt
          - **Feishu**: Send a test message via Feishu Open API, verify receipt

          Report: pairing status, test message sent/received, any issues.
        output: pairing_result
        timeout: 120

    approval:
      required: true
      prompt: |
        Authentication and pairing results for {{channel_type}} ({{channel_name}}):

        Auth: {{auth_result}}
        Pairing: {{pairing_result}}

        Activate this channel for live message routing?

  - name: activate
    steps:
      - id: enable-channel
        agent: self
        prompt: |
          Activate the {{channel_type}} channel "{{channel_name}}" in LetsGo's gateway.

          1. Register the channel in the gateway configuration
          2. Enable inbound message routing for this channel
          3. Enable outbound message delivery for this channel
          4. Send a confirmation message through the channel:
             "LetsGo connected to {{channel_name}} ({{channel_type}}). Ready to assist."

          Report: activation status, confirmation message delivery status.
        output: activation_result
        timeout: 120

      - id: generate-summary
        agent: self
        prompt: |
          Generate a final onboarding summary for {{channel_type}} channel "{{channel_name}}".

          Configuration: {{channel_config}}
          Credentials stored: {{credential_storage}}
          Authentication: {{auth_result}}
          Pairing: {{pairing_result}}
          Activation: {{activation_result}}

          Create a summary report with:
          - **Channel**: Type, name, and connection details
          - **Credentials**: What was stored (names only) and where
          - **Status**: Current channel state (active/inactive)
          - **Features**: What works (send, receive, reactions, threads, etc.)
          - **Limitations**: Any known restrictions or missing features
          - **Next Steps**: Recommended configuration (allowlists, notifications, etc.)
        output: onboarding_summary
        timeout: 180
