schema: v1.7.0

name: setup-wizard
description: Interactive 4-stage setup wizard for LetsGo — provider, channels, satellites, daemon
version: 2.0.0
author: letsgo
tags:
  - setup
  - onboarding
  - wizard

context:
  variables: {}

stages:
  - name: provider-setup
    description: Welcome user and configure AI provider with encrypted secret storage
    steps:
      - id: detect-existing
        agent: self
        prompt: >
          Check for existing LetsGo configuration:
          1. Look for ~/.letsgo/gateway/config.yaml
          2. Check if any secrets are already stored (use secrets tool list_secrets)
          3. If returning user, show what's already configured and ask what to update.
          4. If fresh install, welcome the user and proceed to provider selection.
        output: existing_config
        timeout: 120

      - id: configure-provider
        agent: self
        prompt: >
          Based on detection results: {{existing_config}}

          Walk the user through AI provider setup:
          1. Provider selection: Anthropic / OpenAI / Azure OpenAI / Ollama / Other
          2. Collect the API key or endpoint URL
          3. Store the API key using the secrets tool (set_secret, category: api_key)
          4. Test the provider connection by making a simple API call
          5. Present a summary of the configured provider

          IMPORTANT: Never echo back API keys. Store immediately, confirm storage only.
        output: provider_config
        timeout: 300

    approval:
      required: true
      prompt: |
        Provider configuration complete:

        {{provider_config}}

        Proceed to channel setup?

  - name: channel-setup
    description: Select, install, and configure messaging channels
    steps:
      - id: select-channels
        agent: self
        prompt: >
          Present available messaging channels to the user.

          Use the gateway's channel registry to discover what's available.
          Channels fall into three categories:

          **Built-in (no extra install):**
          - Webhook — HTTP endpoint for integrations
          - WhatsApp — Personal WhatsApp via QR code

          **Optional (pip install required):**
          - Telegram — Bot via @BotFather token
          - Discord — Bot via Developer Portal
          - Slack — Bot via Socket Mode or Events API

          **Plugin channels (separate packages):**
          - Signal — Via signal-cli
          - Matrix — Via matrix-nio
          - Teams — Via Bot Framework

          Ask which channels they want to enable.
          For each selected channel, install dependencies if needed:
          - Telegram: pip install letsgo-gateway[telegram]
          - Discord: pip install letsgo-gateway[discord]
          - Slack: pip install letsgo-gateway[slack]
          - Signal: pip install letsgo-channel-signal
          - Matrix: pip install letsgo-channel-matrix[nio]
          - Teams: pip install letsgo-channel-teams[botbuilder]
        output: selected_channels
        timeout: 300

      - id: configure-channels
        agent: self
        prompt: >
          For each selected channel ({{selected_channels}}), collect credentials:

          **Telegram:** Bot token from @BotFather
          **Discord:** Bot token + Guild ID from Developer Portal
          **Slack:** Bot token (xoxb-) + signing secret + optional app token (xapp-)
          **Webhook:** Endpoint URL + optional shared secret
          **WhatsApp:** No credentials needed (QR code auth at start)
          **Signal:** Phone number for signal-cli registration
          **Matrix:** Homeserver URL + user ID + access token
          **Teams:** Microsoft App ID + App Password from Azure

          Store each credential using secrets tool:
          - Name format: channel/{type}/{name}/{credential}
          - Category: api_key

          Test each channel connection after storing credentials.
          Report results per channel.
        output: channel_config
        timeout: 600

    approval:
      required: true
      prompt: |
        Channel configuration complete:

        {{channel_config}}

        Proceed to satellite bundle selection?

  - name: satellite-setup
    description: Select and install optional satellite bundles
    steps:
      - id: select-satellites
        agent: self
        prompt: >
          Present optional satellite capabilities:

          **Voice** (amplifier-bundle-letsgo-voice)
          - Transcribe inbound voice messages
          - Text-to-speech responses
          - Works across all channels with voice support

          **Canvas** (amplifier-bundle-letsgo-canvas)
          - Rich visual output (charts, HTML, SVG)
          - Web UI at localhost:8080/canvas
          - Auto-render tool outputs

          **WebChat** (amplifier-bundle-letsgo-webchat)
          - Web chat interface
          - Admin dashboard (sessions, channels, cron, usage)

          **Browser** (amplifier-bundle-letsgo-browser)
          - Browser automation via Playwright
          - QR code scanning for WhatsApp setup

          **MCP** (amplifier-bundle-letsgo-mcp)
          - Connect to MCP tool servers
          - Bridge external tools into Amplifier

          Ask which satellites they want. For each selected:
          1. pip install the satellite bundle
          2. Automatically update the user's root bundle.md to add the satellite
             to the includes list. Read the current bundle.md, parse the YAML
             frontmatter, add the satellite to the includes array, and write it back.
             For example, if they select voice and canvas, ensure bundle.md includes:
               - amplifier-bundle-letsgo-voice
               - amplifier-bundle-letsgo-canvas
          3. Verify the updated bundle.md is valid YAML

          Report which satellites were installed and confirm bundle.md was updated.
        output: satellite_config
        timeout: 300

      - id: configure-voice
        agent: self
        prompt: >
          If voice was selected in {{satellite_config}}:

          1. **Transcription provider setup:**
             - Ask: OpenAI Whisper API (recommended, cloud) or local Whisper (free, needs GPU)?
             - If Whisper API: collect API key, store via secrets tool as
               "voice/whisper/api_key" (category: api_key)
             - If local: verify `whisper` CLI is installed

          2. **TTS setup (optional):**
             - Ask: Enable text-to-speech responses? (default: no)
             - If yes, ask provider: edge-tts (free, no key), ElevenLabs (high quality),
               or OpenAI TTS
             - If ElevenLabs: collect API key, store as "voice/elevenlabs/api_key"
             - If OpenAI TTS: can reuse existing OpenAI key if available
             - Choose voice (list top 3 options for selected provider)

          3. **Update gateway config:**
             - Add voice section to ~/.letsgo/gateway/config.yaml with the
               chosen providers and settings
             - Voice config schema:
               voice:
                 enabled: true
                 transcription:
                   provider: "whisper-api" or "local-whisper"
                 tts:
                   enabled: true/false
                   provider: "edge-tts" / "elevenlabs" / "openai-tts"
                   voice: "<chosen-voice>"

          If voice was NOT selected, skip this step entirely and report "Voice: skipped".
        output: voice_config
        timeout: 300

      - id: configure-canvas
        agent: self
        prompt: >
          If canvas was selected in {{satellite_config}}:

          1. **Canvas channel setup:**
             - Ask: What port should the canvas web UI use? (default: 8080)
             - Ask: Bind to localhost only or all interfaces? (default: localhost)
             - Note: The canvas URL will be http://{host}:{port}/canvas

          2. **Install canvas channel package:**
             - Run: pip install letsgo-channel-canvas

          3. **Update gateway config:**
             - Add canvas channel to ~/.letsgo/gateway/config.yaml:
               channels:
                 - name: canvas
                   type: canvas
                   config:
                     host: "<chosen-host>"
                     port: <chosen-port>

          4. **Verify:**
             - Confirm the channel package is installed
             - Report the canvas URL

          If canvas was NOT selected, skip this step entirely and report "Canvas: skipped".
        output: canvas_config
        timeout: 180

      - id: configure-browser
        agent: self
        prompt: >
          If browser was selected in {{satellite_config}}:

          1. **Verify agent-browser CLI:**
             - Run: which agent-browser
             - If not found, install it:
               npm install -g agent-browser && agent-browser install
             - Verify: agent-browser --version

          2. **Report browser readiness:**
             - agent-browser CLI version
             - Chromium status (bundled with agent-browser)
             - Note: No API keys needed — browser automation is local

          If browser was NOT selected, skip this step entirely and report "Browser: skipped".
        output: browser_config
        timeout: 180

      - id: configure-webchat
        agent: self
        prompt: >
          If webchat was selected in {{satellite_config}}:

          1. **WebChat channel setup:**
             - Ask: What port should the webchat server use? (default: 8090)
             - Ask: Bind to localhost only or all interfaces? (default: localhost)
             - Note: Chat will be at http://{host}:{port}/chat
             - Note: Admin dashboard at http://{host}:{port}/admin/

          2. **Admin dashboard setup:**
             - Ask: Enable admin dashboard? (recommended: yes)
             - If yes: Generate a random admin token or let user provide one
             - Store token via secrets tool as "webchat/admin/token" (category: api_key)

          3. **Install webchat channel package:**
             - Run: pip install letsgo-channel-webchat

          4. **Update gateway config:**
             - Add webchat channel to ~/.letsgo/gateway/config.yaml

          If webchat was NOT selected, skip this step entirely and report "WebChat: skipped".
        output: webchat_config
        timeout: 180

      - id: configure-mcp
        agent: self
        prompt: >
          If MCP was selected in {{satellite_config}}:

          1. **Server configuration:**
             - Ask: Do you have any MCP servers to configure? (default: no)
             - If yes, for each server:
               - Name (e.g., "filesystem", "github")
               - Transport: stdio (local subprocess) or streamable-http (remote)
               - For stdio: command to run (e.g., ["npx", "-y", "@modelcontextprotocol/server-filesystem", "/tmp"])
               - For HTTP: URL and optional auth headers
             - Store any API keys/tokens via secrets tool as
               "mcp/{server_name}/token" (category: api_key)

          2. **Update gateway config:**
             - Add mcp section to ~/.letsgo/gateway/config.yaml
             - MCP config schema:
               mcp:
                 servers:
                   <name>:
                     transport: "stdio" or "streamable-http"
                     command: [...] (stdio) or url: "..." (http)

          3. **Test connectivity:**
             - For each configured server, try mcp_call(action="list_tools", server="<name>")
             - Report results

          If MCP was NOT selected, skip this step and report "MCP: skipped".
        output: mcp_config
        timeout: 300

    approval:
      required: true
      prompt: |
        Satellite setup:

        {{satellite_config}}

        Voice configuration: {{voice_config}}

        Canvas configuration: {{canvas_config}}

        Browser configuration: {{browser_config}}

        WebChat configuration: {{webchat_config}}

        MCP configuration: {{mcp_config}}

        Proceed to daemon startup?

  - name: daemon-activate
    description: Start the gateway daemon and verify everything works
    steps:
      - id: create-config
        agent: self
        prompt: >
          Create the gateway daemon configuration file at ~/.letsgo/gateway/config.yaml.

          Include configuration for:
          - All channels from stage 2: {{channel_config}}
          - Heartbeat settings (ask user for interval, default 3600 seconds)
          - Heartbeat channels (which channels should receive heartbeat messages)
          - Tool policy settings (ask if they want careful_mode)

          Write the config file. Report the final configuration (without secrets).
        output: daemon_config
        timeout: 180

      - id: start-daemon
        agent: self
        prompt: >
          Start the LetsGo gateway daemon:

          1. Run: letsgo-gateway --config ~/.letsgo/gateway/config.yaml
          2. Verify all configured channels connect successfully
          3. Send a welcome message through each enabled channel:
             "LetsGo is connected and ready to assist!"
          4. If heartbeat is enabled, verify the heartbeat schedule is active

          Report: daemon status, channel connection status, test message delivery.
        output: daemon_status
        timeout: 300
